#!/usr/bin/env python3
"""Generate a self-signed TLS certificate for the ESP32 HTTPS server.

Produces three artefacts from a single keypair:

  ESP32LEDs/cert.h    C header with PEM strings, #included by the firmware
                      (esp_https_server / mbedtls expect PEM)
  certs/esp32.crt     PEM certificate, pinned by the Python client (verify=)
  certs/esp32.key     PEM private key (used by the firmware; never committed)

An EC P-256 key is used because RSA TLS handshakes are very slow on the ESP32.
The certificate's Subject Alternative Names must cover however the Python client
addresses the device: pass the device's LAN IP with --ip and/or rely on the
default mDNS name (clank-led.local).

Example:
    python3 scripts/generate_esp32_cert.py --ip 192.168.0.18
"""

import argparse
import datetime
import ipaddress
import os
import sys

from cryptography import x509
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.x509.oid import NameOID


def _c_pem(name: str, pem: bytes) -> str:
    """Render a PEM blob as a C string literal (one quoted line per PEM line).

    esp_https_server passes the buffer to mbedtls, which requires PEM input to
    be NUL-terminated; a C string literal provides that automatically, and the
    firmware passes strlen(...) + 1 as the length.
    """
    out = [f"const char {name}[] ="]
    for line in pem.decode("ascii").splitlines():
        out.append(f'  "{line}\\n"')
    out[-1] += ";"
    return "\n".join(out)


def generate(hostname: str, ip: str | None, days_valid: int,
             header_file: str, cert_file: str, key_file: str) -> None:
    key = ec.generate_private_key(ec.SECP256R1())

    subject = issuer = x509.Name([
        x509.NameAttribute(NameOID.ORGANIZATION_NAME, "Clank Voice Assistant"),
        x509.NameAttribute(NameOID.COMMON_NAME, hostname),
    ])

    sans = [x509.DNSName(hostname), x509.DNSName("localhost")]
    if ip:
        sans.append(x509.IPAddress(ipaddress.ip_address(ip)))

    now = datetime.datetime.now(datetime.timezone.utc)
    cert = (
        x509.CertificateBuilder()
        .subject_name(subject)
        .issuer_name(issuer)
        .public_key(key.public_key())
        .serial_number(x509.random_serial_number())
        .not_valid_before(now)
        .not_valid_after(now + datetime.timedelta(days=days_valid))
        .add_extension(x509.SubjectAlternativeName(sans), critical=False)
        .add_extension(
            x509.BasicConstraints(ca=False, path_length=None), critical=True
        )
        .sign(key, hashes.SHA256())
    )

    cert_pem = cert.public_bytes(serialization.Encoding.PEM)
    key_pem = key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption(),
    )

    # C header for the firmware (PEM string literals for esp_https_server)
    os.makedirs(os.path.dirname(header_file) or ".", exist_ok=True)
    with open(header_file, "w") as f:
        f.write("// Auto-generated by scripts/generate_esp32_cert.py — DO NOT COMMIT.\n")
        f.write("// Contains the ESP32's TLS private key.\n")
        f.write("#pragma once\n\n")
        f.write(_c_pem("clank_cert_pem", cert_pem))
        f.write("\n\n")
        f.write(_c_pem("clank_key_pem", key_pem))
        f.write("\n")

    # PEM cert (pinned by the Python client) and key (used by the firmware)
    os.makedirs(os.path.dirname(cert_file) or ".", exist_ok=True)
    with open(cert_file, "wb") as f:
        f.write(cert_pem)
    with open(key_file, "wb") as f:
        f.write(key_pem)
    os.chmod(key_file, 0o600)

    print(f"Wrote firmware header : {header_file}")
    print(f"Wrote pinned PEM cert : {cert_file}")
    print(f"Wrote PEM private key : {key_file}")
    print(f"\nSAN: DNS:{hostname}, DNS:localhost" + (f", IP:{ip}" if ip else ""))
    print("\nNext:")
    print("  1. Re-flash the ESP32 (cert.h is now #included by the firmware).")
    print(f"  2. Point the client at the cert:  export ESP32_CA_CERT={cert_file}")
    if ip:
        print(f"  3. Connect by the matching name:  export ESP32_IP={ip}")


def main() -> None:
    p = argparse.ArgumentParser(description="Generate ESP32 HTTPS certificate")
    p.add_argument("--hostname", default="clank-led.local",
                   help="CN / primary DNS SAN (default: clank-led.local)")
    p.add_argument("--ip", default=None,
                   help="device LAN IP to add as an IP SAN (recommended)")
    p.add_argument("--days", type=int, default=825,
                   help="validity in days (default: 825)")
    p.add_argument("--header-file", default="ESP32LEDs/cert.h")
    p.add_argument("--cert-file", default="certs/esp32.crt")
    p.add_argument("--key-file", default="certs/esp32.key")
    args = p.parse_args()

    try:
        generate(args.hostname, args.ip, args.days,
                 args.header_file, args.cert_file, args.key_file)
    except Exception as e:  # noqa: BLE001
        print(f"Error generating certificate: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
