#!/usr/bin/env bash
# Install + configure the mosquitto MQTT broker for Clank's RGB control.
# Run with sudo:   sudo bash scripts/setup_mosquitto.sh
#
# Reads the broker username/password from ESP32LEDs/secrets.h so the credential
# lives in exactly one place (also used by the ESP32 firmware and Clank's .env).
set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
SECRETS="$REPO/ESP32LEDs/secrets.h"

if [[ $EUID -ne 0 ]]; then
  echo "Please run as root:  sudo bash scripts/setup_mosquitto.sh" >&2
  exit 1
fi
if [[ ! -f "$SECRETS" ]]; then
  echo "secrets.h not found at $SECRETS" >&2
  exit 1
fi

MQTT_USER=$(grep -oP '#define MQTT_USER\s+"\K[^"]+' "$SECRETS")
MQTT_PASS=$(grep -oP '#define MQTT_PASS\s+"\K[^"]+' "$SECRETS")
if [[ -z "$MQTT_USER" || -z "$MQTT_PASS" ]]; then
  echo "MQTT_USER / MQTT_PASS are empty in secrets.h — fill them in first." >&2
  exit 1
fi

# 1. Install mosquitto if missing (Arch/pacman).
if ! command -v mosquitto >/dev/null 2>&1; then
  echo "Installing mosquitto ..."
  pacman -S --needed --noconfirm mosquitto
fi

# 2. Password file (0600, owned by the mosquitto service user).
mosquitto_passwd -b -c /etc/mosquitto/passwd "$MQTT_USER" "$MQTT_PASS"
chown mosquitto:mosquitto /etc/mosquitto/passwd 2>/dev/null || true
chmod 600 /etc/mosquitto/passwd

# 3. Broker config — listen on the LAN so the ESP32 can reach it, require auth.
if [[ -f /etc/mosquitto/mosquitto.conf ]]; then
  cp -n /etc/mosquitto/mosquitto.conf /etc/mosquitto/mosquitto.conf.bak || true
fi
install -d -o mosquitto -g mosquitto /var/lib/mosquitto 2>/dev/null || true
cat > /etc/mosquitto/mosquitto.conf <<'EOF'
# Clank MQTT broker — generated by scripts/setup_mosquitto.sh
persistence true
persistence_location /var/lib/mosquitto/

# Listen on all interfaces so the ESP32 on the LAN can connect.
listener 1883 0.0.0.0
allow_anonymous false
password_file /etc/mosquitto/passwd
EOF

# 4. Enable + (re)start the service.
systemctl enable mosquitto
systemctl restart mosquitto
sleep 1
systemctl --no-pager --full status mosquitto | head -6

echo
echo "mosquitto ready on 1883 (user: $MQTT_USER). Test from this PC with:"
echo "  mosquitto_sub -h 127.0.0.1 -u $MQTT_USER -P '<pass>' -t 'clank/#' -v"
